import { FormValues } from "@/components/form"
import { PostFormMedia } from "@/types/props.type"

export const promptory_types = [
  "text-to-text",
  "text-to-image",
  "text-to-video",
  "text-to-audio",
  "image-to-text",
  "image-to-image",
  "image-to-video",
  "image-to-audio",
  "video-to-text",
  "video-to-image",
  "video-to-video",
  "video-to-audio",
  "audio-to-text",
  "audio-to-image",
  "audio-to-video",
  "audio-to-audio",
]

export const ai_platforms = [
  "chatGPT",
  "Suno",
  "DALL-E",
  "Perplexity",
  "Gemini",
  "Copilot",
  "Whisper",
  "LLaMA",
  "Claude",
  "PaLM ",
  "BERT",
  "Ernie",
  "Midjourney",
  "Runway",
]

export const defaultValues: FormValues = {
  caption: "",
  model_url: "",
  chat_link: "",
  prompt: "",
  response: "",
  promptory_type: promptory_types[0],
  tags: "",
}

export const postMedia: PostFormMedia = {
  prompt: { type: "image", url: "" },
  response: { type: "image", url: "" },
}

export const reservedUsernames = [
  "admin",
  "user",
  "test",
  "home",
  "profile",
  "settings",
  "search",
  "notifications",
  "login",
  "logout",
  "register",
  "signup",
  "signin",
  "account",
  "support",
  "help",
  "dashboard",
  "about",
  "contact",
  "privacy",
  "terms",
  "api",
  "auth",
  "blog",
  "subscribe",
  "unsubscribe",
  "password",
  "confirm",
  "reset",
  "new",
  "delete",
  "edit",
  "update",
  "adminpanel",
  "moderator",
  "messages",
  "files",
  "uploads",
  "downloads",
  "status",
  "feed",
  "explore",
  "activity",
  "archive",
  "community",
  "forum",
  "events",
  "billing",
  "payments",
  "reports",
  "analytics",
  "security",
  "services",
  "projects",
  "settings",
  "terms",
  "api",
  "cookie",
  "upgrade",
  "store",
  "production",
  "testuser",
  "promptories",
  "updates",
  "feedback",
  "friends",
  "followers",
  "likes",
  "shares",
  "groups",
  "avatar",
  "viewer",
  "guest",
  "editor",
  "anonymous",
  "username",
  "name",
]
