export const users = [
  {
    username: "john_doe",
    name: "John Doe",
    email: "john@example.com",
    bio: "Lifelong learner and tech enthusiast.",
    avatar: "https://example.com/avatar1.jpg",
    social_links: { twitter: "@johndoe", github: "@johndoe" },
    followers: [],
    following: [],
  },
  {
    username: "jane_smith",
    name: "Jane Smith",
    email: "jane@example.com",
    bio: "Developer, writer, and world traveler.",
    avatar: "https://example.com/avatar2.jpg",
    social_links: { twitter: "@janesmith", github: "@janesmith" },
    followers: [],
    following: [],
  },
  {
    username: "alice_wonder",
    name: "Alice Wonder",
    email: "alice@example.com",
    bio: "Coding enthusiast and AI researcher.",
    avatar: "https://example.com/avatar3.jpg",
    social_links: { twitter: "@alicewonder", github: "@alicewonder" },
    followers: [],
    following: [],
  },
  {
    username: "bob_builder",
    name: "Bob Builder",
    email: "bob@example.com",
    bio: "Building the future, one line of code at a time.",
    avatar: "https://example.com/avatar4.jpg",
    social_links: { twitter: "@bobbuilder", github: "@bobbuilder" },
    followers: [],
    following: [],
  },
  {
    username: "charlie_coder",
    name: "Charlie Coder",
    email: "charlie@example.com",
    bio: "Front-end developer with a love for design.",
    avatar: "https://example.com/avatar5.jpg",
    social_links: { twitter: "@charliecoder", github: "@charliecoder" },
    followers: [],
    following: [],
  },
  {
    username: "dave_dev",
    name: "Dave Developer",
    email: "dave@example.com",
    bio: "Full-stack developer with 5 years of experience.",
    avatar: "https://example.com/avatar6.jpg",
    social_links: { twitter: "@davedev", github: "@davedev" },
    followers: [],
    following: [],
  },
  {
    username: "eva_engineer",
    name: "Eva Engineer",
    email: "eva@example.com",
    bio: "Engineer passionate about AI and machine learning.",
    avatar: "https://example.com/avatar7.jpg",
    social_links: { twitter: "@evaengineer", github: "@evaengineer" },
    followers: [],
    following: [],
  },
  {
    username: "frankie_future",
    name: "Frankie Future",
    email: "frankie@example.com",
    bio: "Innovator with a focus on futuristic tech.",
    avatar: "https://example.com/avatar8.jpg",
    social_links: { twitter: "@frankiefuture", github: "@frankiefuture" },
    followers: [],
    following: [],
  },
  {
    username: "grace_geek",
    name: "Grace Geek",
    email: "grace@example.com",
    bio: "Geek at heart, always learning something new.",
    avatar: "https://example.com/avatar9.jpg",
    social_links: { twitter: "@gracegeek", github: "@gracegeek" },
    followers: [],
    following: [],
  },
  {
    username: "hannah_hacker",
    name: "Hannah Hacker",
    email: "hannah@example.com",
    bio: "Security expert and ethical hacker.",
    avatar: "https://example.com/avatar10.jpg",
    social_links: { twitter: "@hannahhacker", github: "@hannahhacker" },
    followers: [],
    following: [],
  },
];

export const posts = [
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "Exploring the potential of AI in education.",
    model_url: "https://example.com/model1",
    prompt: "How can AI improve education?",
    response: "AI can personalize learning and provide instant feedback.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Education"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "Advancements in AI and machine learning.",
    model_url: "https://example.com/model2",
    prompt: "What are the latest advancements in AI?",
    response: "AI has made significant progress in NLP and computer vision.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Machine Learning"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "AI in healthcare: Revolutionizing diagnostics.",
    model_url: "https://example.com/model3",
    prompt: "How can AI help in healthcare diagnostics?",
    response: "AI can analyze medical images and assist in early diagnosis.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Healthcare"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "Exploring the future of smart cities.",
    model_url: "https://example.com/model4",
    prompt: "What are smart cities?",
    response: "Smart cities use technology to improve urban living.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["Smart Cities", "Technology"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "How AI is transforming the workforce.",
    model_url: "https://example.com/model5",
    prompt: "How will AI impact jobs?",
    response: "AI will automate repetitive tasks, but create new jobs in tech.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Jobs"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "AI and creativity: Can machines be creative?",
    model_url: "https://example.com/model6",
    prompt: "Can AI generate creative works?",
    response: "AI can assist in creative processes but lacks human intuition.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Creativity"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "Autonomous vehicles and the future of transportation.",
    model_url: "https://example.com/model7",
    prompt: "How do autonomous vehicles work?",
    response: "They use AI to interpret sensory data and navigate roads.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["Autonomous Vehicles", "AI"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "AI and privacy: Striking the right balance.",
    model_url: "https://example.com/model8",
    prompt: "How can we ensure privacy in AI systems?",
    response: "By implementing strong data protection and privacy policies.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Privacy"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "AI and ethics: The moral dilemmas of automation.",
    model_url: "https://example.com/model9",
    prompt: "What are the ethical challenges of AI?",
    response: "AI raises concerns about bias, fairness, and job displacement.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Ethics"],
    views: [],
  },
  {
    user: "66f298b3e3d3563b1f3969ed",
    caption: "AI in the creative industry: Opportunities and challenges.",
    model_url: "https://example.com/model10",
    prompt: "What are the challenges of using AI in creative industries?",
    response: "AI faces hurdles in understanding context and creativity.",
    promptory_type: "text-to-text",
    replies: [],
    likes: [],
    bookmarks: [],
    tags: ["AI", "Creative Industry"],
    views: [],
  },
];
